name: optics
description: >
  Lenses and prisms for Dart objects.
version: 0.0.1
repository: https://github.com/nicholasspencer/dart_optics/tree/main/packages/optics
issue_tracker: https://github.com/nicholasspencer/dart-optics/issues

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  meta: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.16.0
  build_runner: ^2.10.1
  freezed_annotation: ^3.1.0
  freezed: ^3.2.3
